device: "cuda"  # or "cpu"
epoch: 25
lr: 0.0001
optimizer_cooldown: 0
save_dir: "results/baseline1"
batch_size: 16
class_names: ['l-pass', 'r-pass', 'l-spike', 'r_spike', 'l_set', 'r_set', 'l_winpoint', 'r_winpoint']
dataset_path: 'D:/project/Python/DL(Mostafa saad)/Project/VolleyBall/Data'
num_workers: 4
beast_model_path: 'D:\project\Python\DL(Mostafa saad)\Project\VolleyBall\results\baseline1\best_model.pth'
the_scheduler: "ReduceLROnPlateau"